# fly.toml app configuration file generated for send-notes-laravel on 2023-12-25T16:00:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "send-notes-laravel"
primary_region = "bog"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  APP_URL = "https://send-notes-laravel.fly.dev"
  MAIL_MAILER = "smtp"
  MAIL_HOST = "sandbox.smtp.mailtrap.io"
  DB_CONNECTION = "pgsql"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[processes]
  app = ""
  cron = "cron -f"
  worker = "php artisan queue:listen"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
